"""
Formula & Education data – all indicator explanations.
"""
from app.scanner.schemas import FormulaEntry, FormulaResponse

FORMULAS = [
    FormulaEntry(
        name="EMA (Exponential Moving Average)",
        category="Trend",
        formula="EMA = Price × k + EMA(prev) × (1 − k)   where k = 2 ÷ (period + 1)",
        calculation="Each day's EMA gives more weight to recent prices using the smoothing factor k. EMA20 uses k=0.0952, EMA50 uses k=0.0392, EMA200 uses k=0.00995.",
        interpretation="EMA tracks the trend direction. Price above EMA = bullish; below = bearish. Faster EMAs (EMA20) react quicker than slower ones (EMA200).",
        bullish_condition="Price > EMA20 > EMA50 > EMA200 (perfect bullish stack)",
        bearish_condition="Price < EMA20 < EMA50 < EMA200 (perfect bearish stack)",
        example="If RELIANCE is at ₹2900 and EMA20=₹2850, EMA50=₹2800, EMA200=₹2700 → Strong Uptrend signal.",
    ),
    FormulaEntry(
        name="SMA (Simple Moving Average)",
        category="Trend",
        formula="SMA = (P1 + P2 + ... + Pn) ÷ n",
        calculation="Sum of closing prices over N periods divided by N. SMA200 sums last 200 daily closes.",
        interpretation="Shows average price over a period. Less reactive than EMA. Used to identify long-term trend direction.",
        bullish_condition="Price above SMA200 – long-term uptrend confirmed",
        bearish_condition="Price below SMA200 – long-term downtrend",
        example="HDFCBANK SMA200 = ₹1600. Current price ₹1750 → bullish long-term trend.",
    ),
    FormulaEntry(
        name="VWAP (Volume Weighted Average Price)",
        category="Trend",
        formula="VWAP = Σ(Typical Price × Volume) ÷ Σ(Volume)   where Typical Price = (H + L + C) ÷ 3",
        calculation="Cumulative sum of (price × volume) divided by cumulative volume. Resets each trading session.",
        interpretation="VWAP is the fair value benchmark. Institutional buyers target VWAP. Price above VWAP = bullish intraday momentum.",
        bullish_condition="Price > VWAP and rising – institutions are buying",
        bearish_condition="Price < VWAP – selling pressure dominates",
        example="NIFTY VWAP at 22,500. If futures trade at 22,600 → 100pt premium, bullish intraday bias.",
    ),
    FormulaEntry(
        name="RSI (Relative Strength Index)",
        category="Momentum",
        formula="RSI = 100 − [100 ÷ (1 + RS)]   where RS = Avg Gain ÷ Avg Loss over 14 periods",
        calculation="Calculate average gain and average loss over 14 days. RS = avg_gain / avg_loss. RSI oscillates 0–100.",
        interpretation="RSI measures speed and magnitude of price changes. 55–70 is ideal buy zone. >80 overbought, <30 oversold.",
        bullish_condition="RSI 55–70 rising – momentum building without being overbought",
        bearish_condition="RSI < 40 falling – bearish momentum; RSI > 80 – overbought, reversal risk",
        example="TCS RSI = 62 and rising → ideal entry zone. If RSI = 82 → overbought, wait for pullback.",
    ),
    FormulaEntry(
        name="MACD (Moving Average Convergence Divergence)",
        category="Momentum",
        formula="MACD Line = EMA12 − EMA26 | Signal Line = EMA9 of MACD | Histogram = MACD − Signal",
        calculation="Subtract 26-day EMA from 12-day EMA to get MACD line. Smooth it with 9-day EMA for signal. Histogram shows difference.",
        interpretation="Bullish crossover (MACD crosses above Signal) = buy signal. Positive histogram = building momentum.",
        bullish_condition="MACD crosses above Signal line + Histogram turns positive",
        bearish_condition="MACD crosses below Signal line + Histogram turns negative",
        example="INFY: MACD=-2, Signal=-5 → MACD > Signal → bullish crossover confirmed.",
    ),
    FormulaEntry(
        name="ADX (Average Directional Index)",
        category="Trend Strength",
        formula="ADX = 14-period smoothed average of DX   where DX = |+DI − −DI| ÷ (+DI + −DI) × 100",
        calculation="+DI measures upward pressure, −DI downward. DX measures their difference. ADX smooths DX over 14 periods.",
        interpretation="ADX measures trend strength regardless of direction. >25 = strong trend. >40 = very strong. <20 = no trend (sideways).",
        bullish_condition="ADX > 25 AND +DI > −DI – strong bullish trend confirmed",
        bearish_condition="ADX > 25 AND −DI > +DI – strong bearish trend; ADX < 20 = choppy market",
        example="SBIN: ADX=32, +DI=28, -DI=14 → Strong uptrend confirmed. Good momentum setup.",
    ),
    FormulaEntry(
        name="ATR (Average True Range)",
        category="Volatility",
        formula="ATR = 14-period average of True Range   where TR = max(H-L, |H-PrevC|, |L-PrevC|)",
        calculation="True Range is the largest of: today's range, high-to-prev-close gap, low-to-prev-close gap. ATR averages TR over 14 days.",
        interpretation="ATR measures volatility. Used to set stop-losses (1.5×ATR below entry). High ATR = high risk.",
        bullish_condition="Low ATR (< 2% of price) – controlled move, easier to manage risk",
        bearish_condition="ATR > 5% of price – high volatility, wide stops needed, risk of whipsaw",
        example="RELIANCE at ₹2900, ATR=₹45 (1.5%). Stop-loss = 2900 − 1.5×45 = ₹2832.",
    ),
    FormulaEntry(
        name="Supertrend",
        category="Trend Confirmation",
        formula="Upper Band = (H+L)/2 + Multiplier × ATR | Lower Band = (H+L)/2 − Multiplier × ATR | Default: Period=10, Multiplier=3",
        calculation="Calculates ATR-based bands. When price crosses above upper band → BUY. When price crosses below lower band → SELL. Band adjusts with trend.",
        interpretation="Supertrend gives clear BUY/SELL signals with dynamic support/resistance levels. Very effective in trending markets.",
        bullish_condition="Supertrend line is GREEN below price → BUY signal active",
        bearish_condition="Supertrend line is RED above price → SELL signal active",
        example="AXISBANK: Supertrend shows BUY at ₹1050. Price = ₹1120, ST support = ₹1085 → maintain position.",
    ),
    FormulaEntry(
        name="Bollinger Bands",
        category="Volatility",
        formula="Upper = SMA20 + 2×StdDev | Middle = SMA20 | Lower = SMA20 − 2×StdDev",
        calculation="Calculate 20-day SMA and standard deviation. Upper/Lower bands are 2 standard deviations away. ~95% of price action stays within bands.",
        interpretation="Price near upper band = overbought/breakout. Near lower band = oversold/reversal. Squeeze (tight bands) precedes breakout.",
        bullish_condition="Price breaks above upper band with high volume → strong breakout. Price bounces from middle band in uptrend.",
        bearish_condition="Price breaks below lower band → bearish breakdown. Riding lower band = strong downtrend.",
        example="TITAN: BB Upper=₹3800, Middle=₹3600, Lower=₹3400. Price at ₹3850 = above upper band → momentum breakout.",
    ),
    FormulaEntry(
        name="PCR (Put-Call Ratio)",
        category="Options / OI",
        formula="PCR = Total Put OI ÷ Total Call OI",
        calculation="Sum all put option open interest across strikes and expiries. Divide by total call OI.",
        interpretation="PCR > 1 = more puts than calls = bearish sentiment (contrarian: oversold). PCR < 0.7 = excessive calls = complacency (contrarian: overbought).",
        bullish_condition="PCR rising from low levels (0.7–1.0) – fear building, potential reversal up",
        bearish_condition="PCR < 0.5 – too many calls, market complacent, reversal risk down",
        example="Nifty PCR = 1.2 during selloff → excessive put buying → contrarian buy signal.",
    ),
    FormulaEntry(
        name="Open Interest (OI)",
        category="Options / OI",
        formula="OI = Sum of all outstanding futures/options contracts",
        calculation="Each new futures contract adds 1 to OI. Closing a contract reduces OI by 1. OI increases when new money enters the market.",
        interpretation="Rising OI + Rising Price = Long Build-up (bullish). Rising OI + Falling Price = Short Build-up (bearish). Falling OI = positions being closed.",
        bullish_condition="Long Build-up: Price ↑ + OI ↑ = new longs entering",
        bearish_condition="Short Build-up: Price ↓ + OI ↑ = new shorts entering",
        example="ICICIBANK: Price +2% + OI +15% → Long Build-up. Institutional buying confirmed.",
    ),
    FormulaEntry(
        name="Relative Strength (RS)",
        category="Relative Performance",
        formula="RS = Stock Return ÷ Nifty Return (over same period)",
        calculation="Calculate percentage return of stock and Nifty over 20 days. Divide stock return by Nifty return.",
        interpretation="RS > 1 = outperforming Nifty. Rising RS line = improving relative strength. Best stocks show RS > Nifty in both up and down markets.",
        bullish_condition="RS > 1 and RS line making new highs – leader stock",
        bearish_condition="RS < 1 and declining – lagging, avoid or sell",
        example="BHARTIARTL up 8% vs Nifty up 3% in 20 days → RS = 2.67 → strong outperformer.",
    ),
    FormulaEntry(
        name="Momentum",
        category="Momentum",
        formula="Momentum = (Current Price ÷ Price N periods ago) × 100",
        calculation="Divide current close by close N periods (typically 10–20) ago and multiply by 100. >100 = positive momentum.",
        interpretation="Momentum shows rate of price change. Strong momentum stocks tend to continue trending (momentum effect).",
        bullish_condition="Momentum > 105 (5% above N-period ago price) and rising",
        bearish_condition="Momentum < 95 and declining",
        example="MARUTI 20-day momentum = 108 → 8% higher than 20 days ago → strong positive momentum.",
    ),
    FormulaEntry(
        name="Breakout",
        category="Price Action",
        formula="Breakout = Current Price > Highest High of past N days",
        calculation="Find the highest high over 20/50/100/200 days. If today's price exceeds that level = breakout. Volume should confirm (2x+ avg).",
        interpretation="Breakouts from consolidation signal new trend beginning. 52-week breakouts are the most powerful.",
        bullish_condition="Price > 52-week high with 2x volume → institutional accumulation complete",
        bearish_condition="Failed breakout (price quickly returns below level) → bull trap, exit",
        example="BAJFINANCE breaks 52-week high of ₹8200 with 3x volume → strong breakout buy signal.",
    ),
    FormulaEntry(
        name="Volume Analysis",
        category="Volume",
        formula="Volume Ratio = Today's Volume ÷ 20-day Average Volume",
        calculation="Calculate 20-day simple moving average of volume. Divide today's volume by that average.",
        interpretation="High volume confirms price moves. 2x+ volume on breakout = strong conviction. Low volume rally = weak, likely to fail.",
        bullish_condition="Volume > 2x average on up day – institutional buying",
        bearish_condition="Volume > 2x average on down day – institutional selling / panic",
        example="WIPRO rallies 3% on 3.5x volume → confirmed breakout with institutional participation.",
    ),
    FormulaEntry(
        name="Delivery %",
        category="Volume",
        formula="Delivery % = (Delivery Volume ÷ Total Traded Volume) × 100",
        calculation="Delivery volume is shares actually delivered (not squared intraday). Divide by total volume × 100.",
        interpretation="High delivery % (>50%) = investors accumulating for longer term. Low delivery = speculative/intraday trading.",
        bullish_condition="Delivery > 60% on up days – genuine investor buying",
        bearish_condition="Delivery < 20% on high volume – speculative, not reliable",
        example="LT: 65% delivery on +2% day → institutional accumulation confirmed.",
    ),
    FormulaEntry(
        name="Golden Cross",
        category="Trend",
        formula="Golden Cross = EMA50 crosses above EMA200",
        calculation="When the 50-day EMA moves from below to above the 200-day EMA, a Golden Cross forms.",
        interpretation="One of the strongest long-term buy signals. Indicates transition from long-term downtrend to uptrend.",
        bullish_condition="EMA50 crosses above EMA200 → strong long-term buy signal",
        bearish_condition="N/A – look for Death Cross instead",
        example="HDFCBANK EMA50 crossed above EMA200 at ₹1580 → Golden Cross → 6-month uptrend began.",
    ),
    FormulaEntry(
        name="Death Cross",
        category="Trend",
        formula="Death Cross = EMA50 crosses below EMA200",
        calculation="When the 50-day EMA moves from above to below the 200-day EMA, a Death Cross forms.",
        interpretation="Strong long-term sell signal. Indicates transition to long-term downtrend. Institutional selling likely.",
        bullish_condition="N/A – look for Golden Cross recovery instead",
        bearish_condition="EMA50 crosses below EMA200 → strong long-term sell/avoid signal",
        example="INFY Death Cross formed → stock fell 25% over next 3 months. Avoid until Golden Cross.",
    ),
]


def get_formula_response() -> FormulaResponse:
    return FormulaResponse(formulas=FORMULAS, total=len(FORMULAS))
