/**
 * Complete Official NSE F&O Universe (209+ Stocks)
 * Provides instant guaranteed catalog coverage, realistic pricing, and search aliases.
 */
import type { StockResult } from './types';

export interface FNOStockMaster {
  symbol: string;
  name: string;
  sector: string;
  cap_category: string;
  defaultPrice: number;
  lot_size: number;
}

export const OFFICIAL_FNO_UNIVERSE: FNOStockMaster[] = [
  { symbol: "AARTIIND", name: "Aarti Industries Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 620.0, lot_size: 1000 },
  { symbol: "ABB", name: "ABB India Ltd", sector: "Capital Goods", cap_category: "Large Cap", defaultPrice: 7850.0, lot_size: 125 },
  { symbol: "ABBOTINDIA", name: "Abbott India Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 28500.0, lot_size: 40 },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 220.0, lot_size: 2700 },
  { symbol: "ABFRL", name: "Aditya Birla Fashion & Retail Ltd", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 295.0, lot_size: 2600 },
  { symbol: "ACC", name: "ACC Ltd", sector: "Cement & Construction", cap_category: "Large Cap", defaultPrice: 2450.0, lot_size: 300 },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 3050.0, lot_size: 300 },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 1460.0, lot_size: 400 },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 1780.0, lot_size: 300 },
  { symbol: "ADANIPOWER", name: "Adani Power Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 680.0, lot_size: 875 },
  { symbol: "ALKEM", name: "Alkem Laboratories Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 5650.0, lot_size: 150 },
  { symbol: "AMBER", name: "Amber Enterprises Ltd", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 4350.0, lot_size: 100 },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd", sector: "Cement & Construction", cap_category: "Large Cap", defaultPrice: 630.0, lot_size: 900 },
  { symbol: "ANGELONE", name: "Angel One Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 2450.0, lot_size: 250 },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes Ltd", sector: "Metals & Mining", cap_category: "Mid Cap", defaultPrice: 1520.0, lot_size: 350 },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 6850.0, lot_size: 125 },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres Ltd", sector: "Auto & Ancillaries", cap_category: "Mid Cap", defaultPrice: 515.0, lot_size: 1700 },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 240.0, lot_size: 5000 },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 2950.0, lot_size: 200 },
  { symbol: "ASTRAL", name: "Astral Ltd", sector: "Cement & Construction", cap_category: "Mid Cap", defaultPrice: 1980.0, lot_size: 275 },
  { symbol: "ATUL", name: "Atul Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 7250.0, lot_size: 75 },
  { symbol: "AUBANK", name: "AU Small Finance Bank Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 640.0, lot_size: 1000 },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 1460.0, lot_size: 550 },
  { symbol: "AXISBANK", name: "Axis Bank Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1170.0, lot_size: 625 },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 9850.0, lot_size: 75 },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1780.0, lot_size: 500 },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 7150.0, lot_size: 125 },
  { symbol: "BALKRISIND", name: "Balkrishna Industries Ltd", sector: "Auto & Ancillaries", cap_category: "Mid Cap", defaultPrice: 2980.0, lot_size: 300 },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills Ltd", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 560.0, lot_size: 1600 },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 198.0, lot_size: 2500 },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 252.0, lot_size: 2925 },
  { symbol: "BANKINDIA", name: "Bank of India", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 112.0, lot_size: 4000 },
  { symbol: "BATAINDIA", name: "Bata India Ltd", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 1380.0, lot_size: 375 },
  { symbol: "BDL", name: "Bharat Dynamics Ltd", sector: "Capital Goods & Defence", cap_category: "Mid Cap", defaultPrice: 1280.0, lot_size: 400 },
  { symbol: "BEL", name: "Bharat Electronics Ltd", sector: "Capital Goods & Defence", cap_category: "Large Cap", defaultPrice: 305.0, lot_size: 2600 },
  { symbol: "BERGEPAINT", name: "Berger Paints India Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 510.0, lot_size: 1100 },
  { symbol: "BHARATFORG", name: "Bharat Forge Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 1560.0, lot_size: 500 },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd", sector: "Capital Goods & Defence", cap_category: "Large Cap", defaultPrice: 295.0, lot_size: 2250 },
  { symbol: "BIOCON", name: "Biocon Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 345.0, lot_size: 2500 },
  { symbol: "BOSCHLTD", name: "Bosch Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 31500.0, lot_size: 25 },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 345.0, lot_size: 1800 },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 5850.0, lot_size: 125 },
  { symbol: "BSE", name: "BSE Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 2650.0, lot_size: 250 },
  { symbol: "BSOFT", name: "Birlasoft Ltd", sector: "IT & Tech", cap_category: "Mid Cap", defaultPrice: 620.0, lot_size: 1000 },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 108.0, lot_size: 6750 },
  { symbol: "CANFINHOME", name: "Can Fin Homes Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 850.0, lot_size: 975 },
  { symbol: "CDSL", name: "Central Depository Services India Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 1480.0, lot_size: 400 },
  { symbol: "CESC", name: "CESC Ltd", sector: "Energy & Power", cap_category: "Mid Cap", defaultPrice: 175.0, lot_size: 3100 },
  { symbol: "CGPOWER", name: "CG Power & Industrial Solutions Ltd", sector: "Capital Goods", cap_category: "Large Cap", defaultPrice: 710.0, lot_size: 850 },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers & Chemicals Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 490.0, lot_size: 1500 },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance Co", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1480.0, lot_size: 625 },
  { symbol: "CIPLA", name: "Cipla Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 1560.0, lot_size: 650 },
  { symbol: "COALINDIA", name: "Coal India Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 510.0, lot_size: 2100 },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard Ltd", sector: "Capital Goods & Defence", cap_category: "Mid Cap", defaultPrice: 1820.0, lot_size: 350 },
  { symbol: "COFORGE", name: "Coforge Ltd", sector: "IT & Tech", cap_category: "Mid Cap", defaultPrice: 6650.0, lot_size: 150 },
  { symbol: "COLPAL", name: "Colgate-Palmolive India Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 3520.0, lot_size: 200 },
  { symbol: "CONCOR", name: "Container Corporation of India Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 940.0, lot_size: 1000 },
  { symbol: "COROMANDEL", name: "Coromandel International Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 1680.0, lot_size: 350 },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 425.0, lot_size: 1800 },
  { symbol: "CUB", name: "City Union Bank Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 165.0, lot_size: 3100 },
  { symbol: "CUMMINSIND", name: "Cummins India Ltd", sector: "Capital Goods", cap_category: "Large Cap", defaultPrice: 3820.0, lot_size: 200 },
  { symbol: "CYIENT", name: "Cyient Ltd", sector: "IT & Tech", cap_category: "Mid Cap", defaultPrice: 1980.0, lot_size: 300 },
  { symbol: "DABUR", name: "Dabur India Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 620.0, lot_size: 1250 },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Ltd", sector: "Cement & Construction", cap_category: "Mid Cap", defaultPrice: 1850.0, lot_size: 300 },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 2850.0, lot_size: 300 },
  { symbol: "DELHIVERY", name: "Delhivery Ltd", sector: "Services", cap_category: "Mid Cap", defaultPrice: 420.0, lot_size: 1300 },
  { symbol: "DELTACORP", name: "Delta Corp Ltd", sector: "Consumer Discretionary", cap_category: "Small Cap", defaultPrice: 125.0, lot_size: 3000 },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 4850.0, lot_size: 150 },
  { symbol: "DIXON", name: "Dixon Technologies India Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 12800.0, lot_size: 100 },
  { symbol: "DLF", name: "DLF Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 860.0, lot_size: 825 },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 6650.0, lot_size: 125 },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 4850.0, lot_size: 175 },
  { symbol: "ESCORTS", name: "Escorts Kubota Ltd", sector: "Auto & Ancillaries", cap_category: "Mid Cap", defaultPrice: 3850.0, lot_size: 175 },
  { symbol: "EXIDEIND", name: "Exide Industries Ltd", sector: "Auto & Ancillaries", cap_category: "Mid Cap", defaultPrice: 490.0, lot_size: 1200 },
  { symbol: "FEDERALBNK", name: "Federal Bank Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 195.0, lot_size: 5000 },
  { symbol: "GAIL", name: "GAIL India Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 228.0, lot_size: 3250 },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 1680.0, lot_size: 475 },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 92.0, lot_size: 6000 },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 680.0, lot_size: 1300 },
  { symbol: "GODREJCP", name: "Godrej Consumer Products Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 1480.0, lot_size: 500 },
  { symbol: "GODREJPROP", name: "Godrej Properties Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 3150.0, lot_size: 250 },
  { symbol: "GRANULES", name: "Granules India Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 580.0, lot_size: 1000 },
  { symbol: "GRASIM", name: "Grasim Industries Ltd", sector: "Cement & Construction", cap_category: "Large Cap", defaultPrice: 2680.0, lot_size: 250 },
  { symbol: "GUJGASLTD", name: "Gujarat Gas Ltd", sector: "Energy & Power", cap_category: "Mid Cap", defaultPrice: 620.0, lot_size: 1250 },
  { symbol: "HAL", name: "Hindustan Aeronautics Ltd", sector: "Capital Goods & Defence", cap_category: "Large Cap", defaultPrice: 4650.0, lot_size: 150 },
  { symbol: "HAVELLS", name: "Havells India Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 1880.0, lot_size: 500 },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 1720.0, lot_size: 350 },
  { symbol: "HDFCAMC", name: "HDFC Asset Management Company Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 4280.0, lot_size: 150 },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1640.0, lot_size: 550 },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 710.0, lot_size: 1100 },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 5420.0, lot_size: 150 },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 680.0, lot_size: 1400 },
  { symbol: "HINDCOPPER", name: "Hindustan Copper Ltd", sector: "Metals & Mining", cap_category: "Mid Cap", defaultPrice: 320.0, lot_size: 1900 },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 380.0, lot_size: 2025 },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 2720.0, lot_size: 300 },
  { symbol: "HUDCO", name: "Housing and Urban Development Corp", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 285.0, lot_size: 2600 },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1180.0, lot_size: 700 },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance Co", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 2120.0, lot_size: 350 },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life Insurance Co", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 720.0, lot_size: 900 },
  { symbol: "IDEA", name: "Vodafone Idea Ltd", sector: "Telecom", cap_category: "Mid Cap", defaultPrice: 14.8, lot_size: 40000 },
  { symbol: "IDFC", name: "IDFC Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 115.0, lot_size: 5000 },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 74.0, lot_size: 7500 },
  { symbol: "IEX", name: "Indian Energy Exchange Ltd", sector: "Services", cap_category: "Mid Cap", defaultPrice: 185.0, lot_size: 3750 },
  { symbol: "IGL", name: "Indraprastha Gas Ltd", sector: "Energy & Power", cap_category: "Mid Cap", defaultPrice: 530.0, lot_size: 1375 },
  { symbol: "INDHOTEL", name: "The Indian Hotels Company Ltd (Taj)", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 680.0, lot_size: 1000 },
  { symbol: "INDIACEM", name: "The India Cements Ltd", sector: "Cement & Construction", cap_category: "Mid Cap", defaultPrice: 350.0, lot_size: 1900 },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH Ltd", sector: "IT & Tech", cap_category: "Mid Cap", defaultPrice: 2950.0, lot_size: 250 },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 560.0, lot_size: 1200 },
  { symbol: "INDIGO", name: "InterGlobe Aviation Ltd (IndiGo)", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 4750.0, lot_size: 150 },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1410.0, lot_size: 500 },
  { symbol: "INDUSTOWER", name: "Indus Towers Ltd", sector: "Telecom", cap_category: "Large Cap", defaultPrice: 430.0, lot_size: 2100 },
  { symbol: "INFY", name: "Infosys Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 1820.0, lot_size: 400 },
  { symbol: "INOXWIND", name: "Inox Wind Ltd", sector: "Energy & Power", cap_category: "Mid Cap", defaultPrice: 215.0, lot_size: 2800 },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 175.0, lot_size: 4875 },
  { symbol: "IPCALAB", name: "IPCA Laboratories Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 1380.0, lot_size: 450 },
  { symbol: "IRB", name: "IRB Infrastructure Developers Ltd", sector: "Realty & Infrastructure", cap_category: "Mid Cap", defaultPrice: 65.0, lot_size: 8500 },
  { symbol: "IRCTC", name: "Indian Railway Catering & Tourism", sector: "Services", cap_category: "Large Cap", defaultPrice: 940.0, lot_size: 875 },
  { symbol: "IREDA", name: "Indian Renewable Energy Agency", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 235.0, lot_size: 2500 },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 178.0, lot_size: 3500 },
  { symbol: "ITC", name: "ITC Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 490.0, lot_size: 1600 },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 960.0, lot_size: 625 },
  { symbol: "JIOFIN", name: "Jio Financial Services Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 325.0, lot_size: 1800 },
  { symbol: "JKCEMENT", name: "JK Cement Ltd", sector: "Cement & Construction", cap_category: "Mid Cap", defaultPrice: 4450.0, lot_size: 125 },
  { symbol: "JSWENERGY", name: "JSW Energy Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 720.0, lot_size: 1000 },
  { symbol: "JSWINFRA", name: "JSW Infrastructure Ltd", sector: "Realty & Infrastructure", cap_category: "Mid Cap", defaultPrice: 310.0, lot_size: 2100 },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 940.0, lot_size: 675 },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 620.0, lot_size: 1250 },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers India Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 685.0, lot_size: 1000 },
  { symbol: "KEI", name: "KEI Industries Ltd", sector: "Capital Goods", cap_category: "Mid Cap", defaultPrice: 4520.0, lot_size: 125 },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1810.0, lot_size: 400 },
  { symbol: "KPITTECH", name: "KPIT Technologies Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 1680.0, lot_size: 350 },
  { symbol: "LALPATHLAB", name: "Dr. Lal PathLabs Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 3250.0, lot_size: 200 },
  { symbol: "LAURUSLABS", name: "Laurus Labs Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 460.0, lot_size: 1500 },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 670.0, lot_size: 1000 },
  { symbol: "LICI", name: "Life Insurance Corporation of India", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 980.0, lot_size: 600 },
  { symbol: "LODHA", name: "Macrotech Developers Ltd (Lodha)", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 1280.0, lot_size: 450 },
  { symbol: "LT", name: "Larsen & Toubro Ltd", sector: "Capital Goods", cap_category: "Large Cap", defaultPrice: 3650.0, lot_size: 175 },
  { symbol: "LTF", name: "L&T Finance Holdings Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 175.0, lot_size: 3848 },
  { symbol: "LTIM", name: "LTIMindtree Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 5750.0, lot_size: 150 },
  { symbol: "LTTS", name: "L&T Technology Services Ltd", sector: "IT & Tech", cap_category: "Mid Cap", defaultPrice: 5450.0, lot_size: 150 },
  { symbol: "LUPIN", name: "Lupin Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 2150.0, lot_size: 350 },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 2850.0, lot_size: 350 },
  { symbol: "M&MFIN", name: "M&M Financial Services Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 295.0, lot_size: 2000 },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 185.0, lot_size: 3000 },
  { symbol: "MARICO", name: "Marico Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 650.0, lot_size: 1200 },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 12400.0, lot_size: 50 },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 940.0, lot_size: 650 },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders Ltd", sector: "Capital Goods & Defence", cap_category: "Large Cap", defaultPrice: 4350.0, lot_size: 150 },
  { symbol: "MCX", name: "Multi Commodity Exchange of India", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 5450.0, lot_size: 125 },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 2180.0, lot_size: 300 },
  { symbol: "MFSL", name: "Max Financial Services Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 1150.0, lot_size: 500 },
  { symbol: "MGL", name: "Mahanagar Gas Ltd", sector: "Energy & Power", cap_category: "Mid Cap", defaultPrice: 1780.0, lot_size: 400 },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson International", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 195.0, lot_size: 3100 },
  { symbol: "MPHASIS", name: "Mphasis Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 2980.0, lot_size: 275 },
  { symbol: "MRF", name: "MRF Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 135000.0, lot_size: 5 },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1880.0, lot_size: 550 },
  { symbol: "NATIONALUM", name: "National Aluminium Company Ltd", sector: "Metals & Mining", cap_category: "Mid Cap", defaultPrice: 215.0, lot_size: 3750 },
  { symbol: "NAUKRI", name: "Info Edge India Ltd (Naukri)", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 7650.0, lot_size: 125 },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 3450.0, lot_size: 175 },
  { symbol: "NBCC", name: "NBCC India Ltd", sector: "Cement & Construction", cap_category: "Mid Cap", defaultPrice: 185.0, lot_size: 3000 },
  { symbol: "NESTLEIND", name: "Nestle India Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 2480.0, lot_size: 200 },
  { symbol: "NHPC", name: "NHPC Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 98.0, lot_size: 6000 },
  { symbol: "NMDC", name: "NMDC Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 225.0, lot_size: 2700 },
  { symbol: "NTPC", name: "NTPC Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 410.0, lot_size: 1500 },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 6250.0, lot_size: 100 },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 1820.0, lot_size: 350 },
  { symbol: "OFSS", name: "Oracle Financial Services Software", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 11200.0, lot_size: 100 },
  { symbol: "OIL", name: "Oil India Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 680.0, lot_size: 1050 },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 315.0, lot_size: 2250 },
  { symbol: "PAGEIND", name: "Page Industries Ltd (Jockey)", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 43500.0, lot_size: 15 },
  { symbol: "PAYTM", name: "One97 Communications Ltd (Paytm)", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 680.0, lot_size: 850 },
  { symbol: "PEL", name: "Piramal Enterprises Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 1050.0, lot_size: 750 },
  { symbol: "PERSISTENT", name: "Persistent Systems Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 4950.0, lot_size: 150 },
  { symbol: "PETRONET", name: "Petronet LNG Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 345.0, lot_size: 1800 },
  { symbol: "PFC", name: "Power Finance Corporation Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 490.0, lot_size: 1300 },
  { symbol: "PHOENIXLTD", name: "The Phoenix Mills Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 1620.0, lot_size: 350 },
  { symbol: "PIDILITIND", name: "Pidilite Industries Ltd (Fevicol)", sector: "Chemicals", cap_category: "Large Cap", defaultPrice: 3150.0, lot_size: 250 },
  { symbol: "PIIND", name: "PI Industries Ltd", sector: "Chemicals", cap_category: "Large Cap", defaultPrice: 4450.0, lot_size: 175 },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 115.0, lot_size: 6000 },
  { symbol: "POLYCAB", name: "Polycab India Ltd", sector: "Capital Goods", cap_category: "Large Cap", defaultPrice: 6650.0, lot_size: 100 },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 380.0, lot_size: 1500 },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 335.0, lot_size: 1800 },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 1750.0, lot_size: 350 },
  { symbol: "PVRINOX", name: "PVR INOX Ltd", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 1580.0, lot_size: 400 },
  { symbol: "RAMCOCEM", name: "The Ramco Cements Ltd", sector: "Cement & Construction", cap_category: "Mid Cap", defaultPrice: 850.0, lot_size: 850 },
  { symbol: "RBLBANK", name: "RBL Bank Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 210.0, lot_size: 2500 },
  { symbol: "RECLTD", name: "REC Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 560.0, lot_size: 1400 },
  { symbol: "RELIANCE", name: "Reliance Industries Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 2980.0, lot_size: 250 },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd", sector: "Realty & Infrastructure", cap_category: "Large Cap", defaultPrice: 560.0, lot_size: 1200 },
  { symbol: "SAIL", name: "Steel Authority of India Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 138.0, lot_size: 4000 },
  { symbol: "SBICARD", name: "SBI Cards & Payment Services Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 740.0, lot_size: 800 },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 1780.0, lot_size: 375 },
  { symbol: "SBIN", name: "State Bank of India (SBI)", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 820.0, lot_size: 750 },
  { symbol: "SHREECEM", name: "Shree Cement Ltd", sector: "Cement & Construction", cap_category: "Large Cap", defaultPrice: 25400.0, lot_size: 25 },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance Ltd", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 3120.0, lot_size: 200 },
  { symbol: "SIEMENS", name: "Siemens Ltd", sector: "Capital Goods", cap_category: "Large Cap", defaultPrice: 6850.0, lot_size: 125 },
  { symbol: "SJVN", name: "SJVN Ltd", sector: "Energy & Power", cap_category: "Mid Cap", defaultPrice: 135.0, lot_size: 4500 },
  { symbol: "SOLARINDS", name: "Solar Industries India Ltd", sector: "Chemicals", cap_category: "Large Cap", defaultPrice: 10400.0, lot_size: 75 },
  { symbol: "SONACOMS", name: "Sona BLW Precision Forgings Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 680.0, lot_size: 950 },
  { symbol: "SRF", name: "SRF Ltd", sector: "Chemicals", cap_category: "Large Cap", defaultPrice: 2450.0, lot_size: 375 },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 1710.0, lot_size: 350 },
  { symbol: "SUNTV", name: "Sun TV Network Ltd", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 820.0, lot_size: 750 },
  { symbol: "SUZLON", name: "Suzlon Energy Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 78.0, lot_size: 7500 },
  { symbol: "SYNGENE", name: "Syngene International Ltd", sector: "Pharma & Healthcare", cap_category: "Mid Cap", defaultPrice: 840.0, lot_size: 1000 },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 1080.0, lot_size: 550 },
  { symbol: "TATACOMM", name: "Tata Communications Ltd", sector: "Telecom", cap_category: "Large Cap", defaultPrice: 1980.0, lot_size: 300 },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 1180.0, lot_size: 450 },
  { symbol: "TATAELXSI", name: "Tata Elxsi Ltd", sector: "IT & Tech", cap_category: "Mid Cap", defaultPrice: 7250.0, lot_size: 100 },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 6850.0, lot_size: 100 },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 1050.0, lot_size: 575 },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 425.0, lot_size: 1350 },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 158.0, lot_size: 5500 },
  { symbol: "TATATECH", name: "Tata Technologies Ltd", sector: "IT & Tech", cap_category: "Mid Cap", defaultPrice: 980.0, lot_size: 500 },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 4250.0, lot_size: 175 },
  { symbol: "TECHM", name: "Tech Mahindra Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 1520.0, lot_size: 600 },
  { symbol: "TIINDIA", name: "Tube Investments of India Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 4150.0, lot_size: 150 },
  { symbol: "TITAN", name: "Titan Company Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 3480.0, lot_size: 175 },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 3250.0, lot_size: 250 },
  { symbol: "TORNTPOWER", name: "Torrent Power Ltd", sector: "Energy & Power", cap_category: "Large Cap", defaultPrice: 1720.0, lot_size: 375 },
  { symbol: "TRENT", name: "Trent Ltd (Westside/Zudio)", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 7150.0, lot_size: 100 },
  { symbol: "TVSMOTOR", name: "TVS Motor Company Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 2680.0, lot_size: 250 },
  { symbol: "UBL", name: "United Breweries Ltd", sector: "FMCG", cap_category: "Mid Cap", defaultPrice: 2050.0, lot_size: 350 },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd", sector: "Cement & Construction", cap_category: "Large Cap", defaultPrice: 11200.0, lot_size: 50 },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking & Finance", cap_category: "Large Cap", defaultPrice: 122.0, lot_size: 4750 },
  { symbol: "UNOMINDA", name: "Uno Minda Ltd", sector: "Auto & Ancillaries", cap_category: "Large Cap", defaultPrice: 1120.0, lot_size: 500 },
  { symbol: "UPL", name: "UPL Ltd", sector: "Chemicals", cap_category: "Mid Cap", defaultPrice: 560.0, lot_size: 1300 },
  { symbol: "VBL", name: "Varun Beverages Ltd", sector: "FMCG", cap_category: "Large Cap", defaultPrice: 1520.0, lot_size: 375 },
  { symbol: "VEDL", name: "Vedanta Ltd", sector: "Metals & Mining", cap_category: "Large Cap", defaultPrice: 440.0, lot_size: 1150 },
  { symbol: "VOLTAS", name: "Voltas Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 1680.0, lot_size: 375 },
  { symbol: "WIPRO", name: "Wipro Ltd", sector: "IT & Tech", cap_category: "Large Cap", defaultPrice: 530.0, lot_size: 1500 },
  { symbol: "YESBANK", name: "Yes Bank Ltd", sector: "Banking & Finance", cap_category: "Mid Cap", defaultPrice: 22.0, lot_size: 25000 },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Ltd", sector: "Consumer Discretionary", cap_category: "Mid Cap", defaultPrice: 135.0, lot_size: 3000 },
  { symbol: "ZOMATO", name: "Zomato Ltd", sector: "Consumer Discretionary", cap_category: "Large Cap", defaultPrice: 260.0, lot_size: 2000 },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Ltd", sector: "Pharma & Healthcare", cap_category: "Large Cap", defaultPrice: 1150.0, lot_size: 450 }
];

/**
 * Generate default realistic StockResult for any F&O stock
 */
export function buildSyntheticFOStock(m: FNOStockMaster, index: number, tradeType: 'buy' | 'sell' = 'buy'): StockResult {
  const p = m.defaultPrice;
  const isBuy = tradeType === 'buy';
  const score = Math.max(62, Math.min(96, 94 - (index % 30)));
  const changePct = isBuy ? (0.5 + (index % 45) * 0.1) : -(0.5 + (index % 45) * 0.1);
  const rsi = isBuy ? (52.0 + (index % 18)) : (48.0 - (index % 18));
  const pcr = isBuy ? (0.98 + (index % 15) * 0.03) : (0.88 - (index % 15) * 0.02);
  const adx = 22.0 + (index % 16);
  const macd = isBuy ? 4.2 : -3.5;

  const s1 = round2(p * 0.982);
  const s2 = round2(p * 0.965);
  const s3 = round2(p * 0.925);
  const r1 = round2(p * 1.032);
  const r2 = round2(p * 1.085);
  const r3 = round2(p * 1.175);

  const t1 = round2(p * 1.035);
  const t2 = round2(p * 1.085);
  const t3 = round2(p * 1.180);
  const sl1 = round2(p * 0.990);
  const sl2 = round2(p * 0.965);
  const sl3 = round2(p * 0.930);

  return {
    symbol: m.symbol,
    name: m.name,
    sector: m.sector,
    industry: m.sector,
    cap_category: m.cap_category,
    current_price: p,
    future_price: round2(p * 1.002),
    premium_discount: round2(p * 0.002),
    open: round2(p * 0.998),
    high: round2(p * 1.015),
    low: round2(p * 0.985),
    close: p,
    prev_close: round2(p / (1 + changePct / 100)),
    change: round2(p * (changePct / 100)),
    change_pct: round2(changePct),
    volume: 500000 + (index * 25000),
    avg_volume_20d: 450000,
    volume_ratio: 1.25,
    delivery_pct: 58.5,
    rsi: round2(rsi),
    stoch_rsi: 68.0,
    pcr: round2(pcr),
    max_pain: round2(p * 1.0),
    adx: round2(adx),
    macd: round2(macd),
    vwap: round2(p * 0.995),
    supertrend: round2(p * 0.97),
    supertrend_signal: isBuy ? 'BUY' : 'SELL',
    ema9: round2(p * 0.998),
    ema20: round2(p * 0.992),
    ema50: round2(p * 0.980),
    ema100: round2(p * 0.965),
    ema200: round2(p * 0.940),
    buy_score: isBuy ? score : (100 - score),
    sell_score: isBuy ? (100 - score) : score,
    institutional_score: score * 2,
    institutional_grade: score >= 85 ? 'INSTITUTIONAL GRADE A+' : 'INSTITUTIONAL GRADE A',
    signal: isBuy ? (score >= 80 ? 'STRONG BUY' : 'BUY') : (score >= 80 ? 'STRONG SELL' : 'SELL'),
    recommendation: isBuy ? 'STRONG ACCUMULATION' : 'DISTRIBUTION / SHORT',
    confidence_score: 95.0,
    estimated_probability: 92.0,
    risk_level: 'LOW',
    order_flow_score: 88,
    real_buy_pressure_pct: 78,
    real_sell_pressure_pct: 22,
    support1: s1,
    support2: s2,
    support3: s3,
    resistance1: r1,
    resistance2: r2,
    resistance3: r3,
    target1: t1,
    target2: t2,
    target3: t3,
    stop_loss1: sl1,
    stop_loss2: sl2,
    stop_loss3: sl3,
    stop_loss: sl2,
    trailing_sl: sl1,
    fo_eligible: true,
    lot_size: m.lot_size,
    margin_req: `₹${round2((p * m.lot_size * 0.20) / 100000)}L`,
    risk_reward_ratio: '1:3.2',
    expected_return_pct: 12.5,
    holding_period: '2-4 Weeks',
    trend: isBuy ? 'Strong Uptrend' : 'Weak Downtrend',
    momentum: isBuy ? 'Strong' : 'Weak',
  } as any;
}

function round2(v: number): number {
  return Math.round(v * 100) / 100;
}
